EXE  = vecadd
srcs = main.cpp

ifneq ($(CORE0_ONLY),)
    HOSTCONFIG = MyHost.cfg
    $(info *** Only use DSP core 0 as OpenCL compute unit ***)
endif

include ../make_rtos.inc

bin/$(PROFILE)/main.oa15fg: kernel.dsp_h

