std::string dsp_specific_header(
"/*--------------------------------------------------------------------------\n"
"* num_dims = _config_packet[0]\n"
"* G        = _config_packet[1,2,3]\n"
"* S        = _config_packet[4,5,6]\n"
"* F        = _config_packet[7,8,9]\n"
"* t        = _config_packet[10,11,12]\n"
"* unused   = _config_packet[13,14,15]\n"
"*\n"
"* Gi = global_size[i]   is fixed and specified for i in [1..work_dim]\n"
"* Si = local_size[i]    is fixed and specified for i in [1..work_dim]\n"
"* Fi = global_offset[i] is fixed and specified for i in [1..work_dim], \n"
"*                       defaults to [0,0,0]\n"
"*\n"
"* Wi = num_groups[i]  = Gi / Si\n"
"*\n"
"* gi  = global_id[i]  = ti + si\n"
"* si  = local_id[i]\n"
"* wi  = group_id[i]   = (gi - si - Fi) /Si\n"
"* ti  = global_id(i) of workitem 0 in workgroup  = Fi+wi*Si\n"
"*-------------------------------------------------------------------------*/\n"
"\n"
"#define _cfg_addr ((int*)0x00800000) // L2 SRAM\n"
"#define _cfg(i) *(_cfg_addr + i)\n"
"\n"
"#define LOOPS3 for (int s2 = 0; s2 < _cfg(6); ++s2) for (int s1 = 0; s1 < _cfg(5); ++s1) for (int s0 = 0; s0 < _cfg(4); ++s0)\n"
"#define LOOPS2 for (int s1 = 0; s1 < _cfg(5); ++s1) for (int s0 = 0; s0 < _cfg(4); ++s0)\n"
"#define LOOPS1 for (int s0 = 0; s0 < _cfg(4); ++s0)\n"
"#define LOOPS0 \n"
"\n"
"/*--------------------------------------------------------------------------\n"
"* Giving a dimension outside range will surely screw up your system\n"
"*-------------------------------------------------------------------------*/\n"
"#define get_work_dim()       _cfg(0)\n"
"#define get_global_size(i)   _cfg(1+i)\n"
"#define get_global_id(i)     (_cfg(10+i) + s##i)\n"
"#define get_local_size(i)    _cfg(4+i)\n"
"#define get_local_id(i)      (s##i)\n"
"#define get_num_groups(i)    (_cfg(1+i) / _cfg(4+i))\n"
"#define get_group_id(i)      ((_cfg(10+i)-_cfg(7+i)) / _cfg(4+i))\n"
"#define get_global_offset(i) _cfg(7+i)\n"
);

