/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6678",
            customMemoryMap: [
                ["L2SRAM0",   {name: "L2SRAM0",    base: 0x00800000, len: 0x80}],
                ["L2SRAM1",   {name: "L2SRAM1",    base: 0x00800080, len: 0x2bf80}],
                ["L2SRAM",    {name: "L2SRAM",     base: 0x0082c000, len: 0x34000}],
                ["MSMCSRAM",  {name: "MSMCSRAM",   base: 0x0C000000, len: 0x300000}],
                ["DDR3",             {name: "DDR3",             base: 0x80000000, len: 0x3EE00000}],
                ["MSMCSRAM_NOCACHE", {name: "MSMCSRAM_NOCACHE", base: 0xBEE00000, len: 0x100000}],    /* 1M */
                ["DDR3_STATIC",      {name: "DDR3_STATIC",      base: 0xBEF00000, len: 0x100000}],    /* 1M  */
                ["DDR3_NOCACHE0",    {name: "DDR3_NOCACHE0",     base: 0xBF000000, len: 0x800000}],   /* 8M */
                ["DDR3_NOCACHE1",    {name: "DDR3_NOCACHE1",     base: 0xBF800000, len: 0x800000}],   /* 8M */
            ],
            l1DMode:"32k",
            l1PMode:"32k",
            l2Mode:"128k",
    });
    
instance :
    
    override config string codeMemory  = "DDR3_STATIC";   
    override config string dataMemory  = "MSMCSRAM_NOCACHE";
    override config string stackMemory = "L2SRAM1";
    
}
