class event_list():
    """Dictionary of Event Offset Numbers and AET EVENT Names from AET LIB"""

    mem_events = {
        0: 'AET_GEM_MEM_EVT_START + 0',
        1: 'AET_GEM_MEM_EVT_START + 1',
        2: 'AET_GEM_MEM_EVT_START + 2',
        3: 'AET_GEM_MEM_EVT_START + 3',
        4: 'AET_GEM_MEM_EVT_START + 4',
        5: 'AET_GEM_MEM_EVT_START + 5',
        6: 'AET_GEM_MEM_EVT_START + 6',
        7: 'AET_GEM_MEM_EVT_START + 7',
        8: 'AET_GEM_MEM_EVT_START + 8',
        9: 'AET_GEM_MEM_EVT_START + 9',
        10: 'AET_GEM_MEM_EVT_START + 10',
        11: 'AET_GEM_MEM_EVT_START + 11',
        12: 'AET_GEM_MEM_EVT_START + 12',
        13: 'AET_GEM_MEM_EVT_START + 13',
        14: 'AET_GEM_MEM_EVT_START + 14',
        15: 'AET_GEM_MEM_EVT_START + 15',
        16: 'AET_GEM_MEM_EVT_START + 16',
        17: 'AET_GEM_MEM_EVT_START + 17',
        18: 'AET_GEM_MEM_EVT_START + 18',
        19: 'AET_GEM_MEM_EVT_START + 19',
        20: 'AET_GEM_MEM_EVT_START + 20',
        21: 'AET_GEM_MEM_EVT_START + 21',
        22: 'AET_GEM_MEM_EVT_START + 22',
        23: 'AET_GEM_MEM_EVT_START + 23',
        24: 'AET_GEM_MEM_EVT_START + 24',
        25: 'AET_GEM_MEM_EVT_START + 25',
        26: 'AET_GEM_MEM_EVT_START + 26',
        27: 'AET_GEM_MEM_EVT_START + 27',
        28: 'AET_GEM_MEM_EVT_START + 28',
        29: 'AET_GEM_MEM_EVT_START + 29'
    }

    stall_events = {
        0: 'AET_GEM_STALL_EVT_START + 0',
        1: 'AET_GEM_STALL_EVT_START + 1',
        2: 'AET_GEM_STALL_EVT_START + 2',
        3: 'AET_GEM_STALL_EVT_START + 3',
        4: 'AET_GEM_STALL_EVT_START + 4',
        5: 'AET_GEM_STALL_EVT_START + 5',
        6: 'AET_GEM_STALL_EVT_START + 6',
        8: 'AET_GEM_STALL_EVT_START + 8',
        10: 'AET_GEM_STALL_EVT_START + 10',
        11: 'AET_GEM_STALL_EVT_START + 11',
        12: 'AET_GEM_STALL_EVT_START + 12',
        13: 'AET_GEM_STALL_EVT_START + 13',
        14: 'AET_GEM_STALL_EVT_START + 14',
        15: 'AET_GEM_STALL_EVT_START + 15',
        16: 'AET_GEM_STALL_EVT_START + 16',
        17: 'AET_GEM_STALL_EVT_START + 17',
        18: 'AET_GEM_STALL_EVT_START + 18',
        20: 'AET_GEM_STALL_EVT_START + 20',
        21: 'AET_GEM_STALL_EVT_START + 21',
        22: 'AET_GEM_STALL_EVT_START + 22',
    }
